# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesign/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(606, 200)
        MainWindow.setStyleSheet("background-color:rgb(26, 24, 24);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 70, 102, 23))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(243, 243, 243);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.labelRetorno = QtWidgets.QLabel(self.centralwidget)
        self.labelRetorno.setGeometry(QtCore.QRect(10, 100, 591, 61))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(87)
        self.labelRetorno.setFont(font)
        self.labelRetorno.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelRetorno.setStyleSheet("color: green;\n"
"font-weight: 700;\n"
"\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: rgb(243, 243, 243);")
        self.labelRetorno.setText("")
        self.labelRetorno.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRetorno.setObjectName("labelRetorno")
        self.inputValidaCpf = QtWidgets.QLineEdit(self.centralwidget)
        self.inputValidaCpf.setGeometry(QtCore.QRect(125, 17, 261, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        self.inputValidaCpf.setFont(font)
        self.inputValidaCpf.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.inputValidaCpf.setObjectName("inputValidaCpf")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(8, 17, 112, 23))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(243, 243, 243);")
        self.label_2.setObjectName("label_2")
        self.btnValidaCpf = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidaCpf.setGeometry(QtCore.QRect(398, 17, 200, 30))
        self.btnValidaCpf.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(87)
        self.btnValidaCpf.setFont(font)
        self.btnValidaCpf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnValidaCpf.setStyleSheet("QPushButton {\n"
"color: rgb(243, 243, 243);\n"
"font-weight: 700;\n"
"background-color: rgb(32, 74, 135);\n"
"border-width: 3px;\n"
"border-radius: 15px;\n"
"border-color: rgb(243, 243, 243);\n"
"cursor: pointer;\n"
"}\n"
"QPushButton:hover {\n"
"border-style: outset;\n"
"color: rgb(243, 243, 243);\n"
"font-weight: 700;\n"
"background-color: rgb(32, 74, 135);\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: rgb(243, 243, 243);\n"
"cursor: pointer;\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"color: rgb(243, 243, 243);\n"
"font: 14pt \"DejaVu Sans\";\n"
"font-weight: 700;\n"
"background-color: rgb(32, 74, 135);\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: rgb(243, 243, 243);\n"
"cursor: pointer;\n"
"}")
        self.btnValidaCpf.setObjectName("btnValidaCpf")
        self.btnGeraCpf = QtWidgets.QPushButton(self.centralwidget)
        self.btnGeraCpf.setGeometry(QtCore.QRect(398, 62, 201, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(87)
        self.btnGeraCpf.setFont(font)
        self.btnGeraCpf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGeraCpf.setStyleSheet("QPushButton {\n"
"color: rgb(243, 243, 243);\n"
"font-weight: 700;\n"
"background-color: rgb(32, 74, 135);\n"
"border-width: 3px;\n"
"border-radius: 15px;\n"
"border-color: rgb(243, 243, 243);\n"
"cursor: pointer;\n"
"}\n"
"QPushButton:hover {\n"
"border-style: outset;\n"
"color: rgb(243, 243, 243);\n"
"font-weight: 700;\n"
"background-color: rgb(32, 74, 135);\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: rgb(243, 243, 243);\n"
"cursor: Pointing Hand;\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"color: rgb(243, 243, 243);\n"
"font: 14pt \"DejaVu Sans\";\n"
"font-weight: 700;\n"
"background-color: rgb(32, 74, 135);\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: rgb(243, 243, 243);\n"
"}")
        self.btnGeraCpf.setObjectName("btnGeraCpf")
        self.btnCopiarCpf = QtWidgets.QPushButton(self.centralwidget)
        self.btnCopiarCpf.setGeometry(QtCore.QRect(480, 170, 121, 24))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(87)
        self.btnCopiarCpf.setFont(font)
        self.btnCopiarCpf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCopiarCpf.setStyleSheet("QPushButton {\n"
"color: rgb(243, 243, 243);\n"
"background-color: none;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: rgb(243, 243, 243);\n"
"font-weight: 700;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: none;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: blue;\n"
"}\n"
"QPushButton:pressed {\n"
"font: 57 10pt \"Ubuntu Medium\";\n"
"font-weight: 700;\n"
"color: white;\n"
"background-color: none;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: blue;\n"
"}\n"
"")
        self.btnCopiarCpf.setObjectName("btnCopiarCpf")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 171, 17))
        self.label_3.setStyleSheet("color: white;\n"
"font-weight: 700;")
        self.label_3.setObjectName("label_3")
        self.btnLinkDayan = QtWidgets.QPushButton(self.centralwidget)
        self.btnLinkDayan.setGeometry(QtCore.QRect(180, 180, 161, 16))
        self.btnLinkDayan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLinkDayan.setStyleSheet("QPushButton {\n"
"color: white;\n"
"font-weight: 700;\n"
"border: none;\n"
"height: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(114, 159, 207);\n"
"font-weight: 700;\n"
"border: none;\n"
"height: 1px;\n"
"text-decoration: underline;\n"
"font-style: italic;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"font-weight: 700;\n"
"border: none;\n"
"height: 1px;\n"
"text-decoration: underline;\n"
"font-style: italic;\n"
"}")
        self.btnLinkDayan.setObjectName("btnLinkDayan")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gerar e Validar Cpf"))
        self.label.setText(_translate("MainWindow", "Gerar CPF:"))
        self.label_2.setText(_translate("MainWindow", "Validar Cpf:"))
        self.btnValidaCpf.setText(_translate("MainWindow", "VALIDAR"))
        self.btnGeraCpf.setText(_translate("MainWindow", "GERAR"))
        self.btnCopiarCpf.setText(_translate("MainWindow", "Copiar/Validar"))
        self.label_3.setText(_translate("MainWindow", ">>> Desenvolvido por"))
        self.btnLinkDayan.setText(_translate("MainWindow", "Dayan Ramos Gomes"))
